package com.saam.microservices.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Estadistica generated by hbm2java
 */
@Entity
@Table(name = "estadistica", catalog = "smart_crop")
public class Estadistica {

	private Long id;

	private Cultivo cultivo;

	private Estacion estacion;

	private String ip;

	private int temperatura;

	private int humedad;

	public Estadistica() {
	}

	public Estadistica(Cultivo cultivo, Estacion estacion, String ip, int temperatura, int humedad) {
		this.cultivo = cultivo;
		this.estacion = estacion;
		this.ip = ip;
		this.temperatura = temperatura;
		this.humedad = humedad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cultivo_id", nullable = false)
	public Cultivo getCultivo() {
		return this.cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estacion_id", nullable = false)
	public Estacion getEstacion() {
		return this.estacion;
	}

	public void setEstacion(Estacion estacion) {
		this.estacion = estacion;
	}

	@Column(name = "ip", nullable = false, length = 20)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "temperatura", nullable = false)
	public int getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(int temperatura) {
		this.temperatura = temperatura;
	}

	@Column(name = "humedad", nullable = false)
	public int getHumedad() {
		return this.humedad;
	}

	public void setHumedad(int humedad) {
		this.humedad = humedad;
	}
}
