package com.saam.microservices.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.saam.microservices.model.Estacion.Basico;

/**
 * TipoCultivo generated by hbm2java
 */
@Entity
@Table(name = "tipo_cultivo", catalog = "smart_crop")
public class TipoCultivo {
	
	public interface Basicos{}

	@JsonView(Basico.class)	
	private Long id;

	@JsonView(Basico.class)
	private String nombre;

	@JsonView(Basico.class)
	private int humedadMin;

	@JsonView(Basico.class)
	private int humedadMax;

	@JsonView(Basico.class)
	private int temperaturaMin;

	@JsonView(Basico.class)
	private int temperaturaMax;

	@JsonView(Basico.class)
	private int periodoRiego;

	private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);

	private Set<Cultivo> cultivos_1 = new HashSet<Cultivo>(0);

	public TipoCultivo() {
	}

	public TipoCultivo(String nombre, int humedadMin, int humedadMax, int temperaturaMin, int temperaturaMax,
			int periodoRiego) {
		this.nombre = nombre;
		this.humedadMin = humedadMin;
		this.humedadMax = humedadMax;
		this.temperaturaMin = temperaturaMin;
		this.temperaturaMax = temperaturaMax;
		this.periodoRiego = periodoRiego;
	}

	public TipoCultivo(String nombre, int humedadMin, int humedadMax, int temperaturaMin, int temperaturaMax,
			int periodoRiego, Set<Cultivo> cultivos, Set<Cultivo> cultivos_1) {
		this.nombre = nombre;
		this.humedadMin = humedadMin;
		this.humedadMax = humedadMax;
		this.temperaturaMin = temperaturaMin;
		this.temperaturaMax = temperaturaMax;
		this.periodoRiego = periodoRiego;
		this.cultivos = cultivos;
		this.cultivos_1 = cultivos_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "humedad_min", nullable = false)
	public int getHumedadMin() {
		return this.humedadMin;
	}

	public void setHumedadMin(int humedadMin) {
		this.humedadMin = humedadMin;
	}

	@Column(name = "humedad_max", nullable = false)
	public int getHumedadMax() {
		return this.humedadMax;
	}

	public void setHumedadMax(int humedadMax) {
		this.humedadMax = humedadMax;
	}

	@Column(name = "temperatura_min", nullable = false)
	public int getTemperaturaMin() {
		return this.temperaturaMin;
	}

	public void setTemperaturaMin(int temperaturaMin) {
		this.temperaturaMin = temperaturaMin;
	}

	@Column(name = "temperatura_max", nullable = false)
	public int getTemperaturaMax() {
		return this.temperaturaMax;
	}

	public void setTemperaturaMax(int temperaturaMax) {
		this.temperaturaMax = temperaturaMax;
	}

	@Column(name = "periodo_riego", nullable = false)
	public int getPeriodoRiego() {
		return this.periodoRiego;
	}

	public void setPeriodoRiego(int periodoRiego) {
		this.periodoRiego = periodoRiego;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCultivo")
	public Set<Cultivo> getCultivos() {
		return this.cultivos;
	}

	public void setCultivos(Set<Cultivo> cultivos) {
		this.cultivos = cultivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCultivo")
	public Set<Cultivo> getCultivos_1() {
		return this.cultivos_1;
	}

	public void setCultivos_1(Set<Cultivo> cultivos_1) {
		this.cultivos_1 = cultivos_1;
	}
}
